version: "3"
services:
  #MySQL Database image
  my_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8XX(9pS@a1
      MYSQL_DATABASE: thefirst_wp981
      MYSQL_USER: thefirst_wp981
      MYSQL_PASSWORD: 8XX(9pS@a1
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - my_database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my_database
      MYSQL_ROOT_PASSWORD: 8XX(9pS@a1

  #WordPress image based on Apache
  wordpress:
    depends_on:
      - my_database
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: my_database:3306
      WORDPRESS_DB_USER: thefirst_wp981
      WORDPRESS_DB_PASSWORD: 8XX(9pS@a1
      WORDPRESS_DB_NAME: thefirst_wp981
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}
